# Add configuration values here, as shown below.
#



price_vip: '10'
price_platinum: '20'

braintree_merchant_id: 'your-merchant_id'
braintree_public_key: 'your-public_key'
braintree_private_key: 'your-private_key'

